- name: Audit IOS-XR BFG Configuration
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_port: 22
    ansible_network_os: iosxr
    ansible_python_interpreter: /Users/gmonne/.pyenv/shims/python
  tasks:
    - name: Get Neighbors
      import_tasks: './tasks/get_neighbors.yml'
      vars:
        ansible_connection: netconf
        ansible_port: 830
    
    - name: Check if BFD is enabled
      iosxr_command:
        match: all
        commands: "show bgp neighbors {{ item['neighbor-address'] }}"
        wait_for: 
          - result[0] contains 'BFD enabled'
      loop: '{{ neighbors }}'
      ignore_errors: yes