---
- hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: iosxr
  # roles:
  #   - name: ansible-network.cisco_iosxr
  #     function: config_manager/get
  tasks:
    - name: collect facts from iosxr devices
      include_role:
        name: ansible-network.cisco_iosxr
        tasks_from: config_manager/get