---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: iosxr
    ansible_python_interpreter: /Users/gmonne/.pyenv/shims/python
  tasks:
    - name: Get Neighbor-Groups
      import_tasks: './tasks/get_neighbor_groups.yml'
      vars:
        ansible_connection: netconf
        ansible_port: 830

