- name: Get running-config
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_port: 22
    ansible_network_os: iosxr  
  tasks:        
    - name: Get running config
      iosxr_command:
        match: all
        commands: "show running-config"
      register: output
