---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: netconf
    ansible_network_os: default
    ansible_user: conatel
    ansible_password: C0n4t3l
    ansible_port: 830
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Get running configuration and state data
      netconf_get:
        display: xml
        source: running
      register: output

    - xml:
        xmlstring: '{{ output["stdout_lines"] | join("") }}'
        xpath: '/x:data/y:bgp/y:instance/y:instance-as/y:four-byte-as/y:default-vrf/y:global/y:router-id'
        content: text
        namespaces:
          x: urn:ietf:params:xml:ns:netconf:base:1.0
          y: http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-bgp-cfg 
      register: output

    - debug:
        var: output

