---
- hosts: all
  gather_facts: true
  vars:
    ansible_connection: netconf
    ansible_network_os: iosxr
    ansible_user: conatel
    ansible_password: C0n4t3l
    ansible_port: 830
  tasks:
    - name: Get running configuration and state data
      netconf_get:
        display: pretty
        source: running
      register: output

    - debug:
        var: { output["stdout"] }
