---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: netconf
    ansible_port: 830
  tasks:
    - name: Get running configuration and state data
      netconf_get:
        display: json
      register: output

    - debug:
        var: output
