---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: netconf
    ansible_network_os: default
    ansible_user: conatel
    ansible_password: C0n4t3l
    ansible_port: 830
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Get Neighbor Groups
      netconf_get:
        display: json
        source: running
        filter: >
          <bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-bgp-cfg">
            <instance>
              <instance-as>
                <four-byte-as>
                  <default-vrf>
                    <bgp-entity>
                      <neighbor-groups />
                    </bgp-entity>
                  </default-vrf>
                </four-byte-as>
              </instance-as>
            </instance>
          </bgp>
        lock: never
      register: json_output

    - debug:
        var: json_output

    - name: Get neighbors
      netconf_get:
        display: json
        source: running
        filter: >
          <bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-bgp-cfg">
            <instance>
              <instance-as>
                <four-byte-as>
                  <default-vrf>
                    <bgp-entity>
                      <neighbors />
                    </bgp-entity>
                  </default-vrf>
                </four-byte-as>
              </instance-as>
            </instance>
          </bgp>
        lock: never
      register: json_output

    - debug:
        var: json_output

