---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: netconf
    ansible_network_os: iosxr
    ansible_user: conatel
    ansible_password: C0n4t3l
    ansible_port: 830
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Get running configuration and state data
      netconf_get:
        display: xml
        source: running
        filter: '<bgp><instance /></bgp>'
      register: output

    - debug:
        var: output["stdout"]
