---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: iosxr
  tasks:
    - name: Retrieve IOS-XR version
      iosxr_command:
        commands: show version
      when: ansible_network_os == 'iosxr'
      register: output

    - debug:
        var: output
