---
- hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: iosxr
    ansible_python_interpreter: /Users/gmonne/.pyenv/shims/python
  tasks:
    - name: Retrieve IOS-XR version
      iosxr_command:
        commands: >
          show running-config
      when: ansible_network_os == 'iosxr'
      register: output
  